#!/usr/bin/env bash
# This sets up a server to listen on port 80 across all active IPv4 addresses on servers.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
