#!/usr/bin/env bash
# This configures a server to listen on port 80 for all active IPv4 IPs of servers.

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
