#!/usr/bin/env bash
# Ifinitely writes "I am alive" to the file /tmp/my_process.
#   Sleeps for 2 seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
