#!/usr/bin/env bash
# Uses while loop to display "Best School" 10 times.
#   On the 9th iteration, it displays "Hi" before "Best School".

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counter++ ))
done
