#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Displays only the part of the name after the first dash. 

Alist=$(ls)
for i in $Alist; do
  echo "$i" | cut -d '-' -f2
done
